# Token-based login for the admin UI.
# ADMIN_TOKEN is generated by run.sh and passed as env var.
# Visit /auth/<token> to authenticate — run.sh prints a clickable link.

class SessionsController < AdminController
  skip_before_action :require_auth

  # GET /auth/:token — click the link from run.sh, get a cookie, go to dashboard
  def create
    if params[:token].present? && ActiveSupport::SecurityUtils.secure_compare(params[:token], admin_token)
      session[:authenticated] = true
      redirect_to root_path
    else
      render plain: "Invalid token.", status: :unauthorized
    end
  end

  def destroy
    reset_session
    render plain: "Logged out."
  end

  private

  def admin_token
    ENV.fetch("ADMIN_TOKEN")
  end
end
