default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/manager_development.sqlite3

test:
  <<: *default
  database: db/manager_test.sqlite3

production:
  <<: *default
  # Database file on persistent volume mount at /data
  database: /data/manager_production.sqlite3
